EventReg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('users/', include('users.urls')), 
    path('users/', include('django.contrib.auth.urls')),
    
    # we want to have our home.html template appear as the homepage. But we don’t want to build a
    # dedicated pages app just yet, so we can use the shortcut of importing TemplateView
    # and setting the template_name right in our url pattern
    path('', TemplateView.as_view(template_name='home.html'),name='home'), 

    path('sport_events/',include(('sport_events.urls','sport_events'),namespace='sport_events'), name='sport_events'),
]

sport_events/urls.py
from django.urls import path
from sport_events import views

app_name = 'sport_events'

urlpatterns = [
    path('', views.SportEventsHomeView.as_view(), name='sport_events_home'),
    
    path('active_events/', views.ActiveEventListView.as_view(), name='active_events'),
    path('closed_events/', views.ClosedEventListView.as_view(), name='closed_events'),
    path('completed_events/', views.CompletedEventListView.as_view(), name='completed_events'),
    path('my_events/', views.MyEventListView.as_view() , name='my_events'),
    
    path('event/<int:pk>/', views.EventDetailView.as_view() , name='event_detail'),
    path('event/<int:pk>/register/', views.register , name='register'),
    path('event/<int:pk>/schedule/', views.schedule , name='schedule'),

    path('match/<int:pk>/update/', views.MatchUpdateView.as_view() , name='match_update'),
]

users/urls.py
from django.urls import path
from users.views import SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

sport_events/models.py
from django.db import models
from django.urls import reverse
from users.models import CustomUser

# Create your models here.


class Sport(models.Model):
    sport_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.sport_name


class Event(models.Model):

    ELIGIBLE_CHOICES    = models.TextChoices('eligible_user_type', 'STUDENT TEACHER').choices
    STATUS_CHOICES      = models.TextChoices('status', 'ACTIVE CLOSED COMPLETED').choices

    name                = models.CharField(max_length=50)
    description         = models.TextField()
    sport               = models.ForeignKey(Sport, on_delete=models.SET('Deleted Sport'), related_name='events')
    fee                 = models.IntegerField(default=0)
    venue               = models.CharField(max_length=50)
    date_time           = models.DateTimeField(auto_now=False, auto_now_add=False)  # Use timeone instead
    reg_close_date      = models.DateField(auto_now=False, auto_now_add=False)
    eligible_user_type  = models.CharField(choices=ELIGIBLE_CHOICES, max_length=10)  

    status              = models.CharField(choices=STATUS_CHOICES, max_length=10)
    curr_round          = models.IntegerField(default=0)
    participants        = models.ManyToManyField(CustomUser,blank=True)

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("event_detail", kwargs={"pk": self.pk})    

    def complete(self):
        print(self.status)
        self.status = 'COMPLETED'
        print(self.name)
        print(self.status)



class Match(models.Model):

    event           = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='matches')
    participant_1   = models.ForeignKey(CustomUser, on_delete=models.SET('Deleted user'), related_name='participant_1')
    participant_2   = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.SET('Deleted user'), related_name='participant_2')
    round_no        = models.IntegerField()
    winner          = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.SET('Deleted user'), related_name='winner')

    class Meta:
        verbose_name = "Match"
        verbose_name_plural = "Matches"

    def __str__(self):
        s = self.participant_1.username+" "
        if self.participant_2:
            s = s +  self.participant_2.username
        return s

    def get_absolute_url(self):
        return reverse("sport_events:event_detail", kwargs={"pk": self.event.pk})




'''
SELECT CONCAT('DROP TABLE ', TABLE_NAME, ';')
FROM INFORMATION_SCHEMA.tables
WHERE TABLE_SCHEMA = 'event_reg_db'

DROP TABLE auth_group;                        
DROP TABLE auth_group_permissions;            
DROP TABLE auth_permission;                   
DROP TABLE django_admin_log;                  
DROP TABLE django_content_type;               
DROP TABLE django_migrations;                 
DROP TABLE django_session;                    
DROP TABLE users_customuser;                  
DROP TABLE users_customuser_groups;           
DROP TABLE users_customuser_user_permissions; 
'''

sport_events/forms.py
from django import forms
from django.utils import timezone
from .models import Match
from users.models import CustomUser
from django.db.models import Q


class MatchForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = "__all__" # for Django 1.8+


    def __init__(self, *args, **kwargs):
        super(MatchForm, self).__init__(*args, **kwargs)
        if self.instance:
            if self.instance.participant_2 is None:
                self.fields['winner'].queryset = CustomUser.objects.filter(pk=self.instance.participant_1.pk) 
            else:
                self.fields['winner'].queryset = CustomUser.objects.filter(Q(pk=self.instance.participant_1.pk) | Q(pk=self.instance.participant_2.pk) )

sport_events/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView
from .models import Event,Match
from django.shortcuts import redirect
from django.urls import reverse
from django.db import transaction
from .forms import MatchForm
from django.db.models import Max
from users.models import CustomUser
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test

# Create your views here.

class ActiveEventListView(ListView):
    template_name = "sport_events/active_events_list.html"

    def get_queryset(self):
        return Event.objects.filter(status='ACTIVE')
    
    
class ClosedEventListView(ListView):
    template_name = "sport_events/closed_events_list.html"

    def get_queryset(self):
        return Event.objects.filter(status='CLOSED')


class CompletedEventListView(ListView):
    template_name = "sport_events/completed_events_list.html"

    def get_queryset(self):
        return Event.objects.filter(status='COMPLETED')


class MyEventListView(LoginRequiredMixin,ListView):
    template_name = "sport_events/my_events_list.html"

    def get_queryset(self):
        return self.request.user.event_set.all()


class EventDetailView(LoginRequiredMixin,DetailView):
    model = Event
    template_name = "sport_events/event_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_registered'] = False
        if self.request.user in self.object.participants.all():
            context['is_registered'] = True
        # context['is_staff'] = self.request.user.is_staff 
        context['matches'] = self.object.matches.filter(round_no=self.object.curr_round)

        if self.object.status == 'COMPLETED':
            res = self.object.matches.all().aggregate(Max('round_no'))
            winner = self.object.matches.filter(round_no=res['round_no__max'])[0].winner
            context['winner'] = winner 
            
        return context




@login_required
def register(request,pk):
    event = get_object_or_404(Event, pk=pk)
    if request.user.is_teacher:
        user_type = 'TEACHER'
    else: 
        user_type = 'STUDENT'    

    if event.status=='ACTIVE' and event.eligible_user_type == user_type:
        event.participants.add(request.user)
        return redirect(reverse('sport_events:active_events'))        

    return redirect(reverse('sport_events:event_detail', kwargs={'pk':pk}))




class SportEventsHomeView(TemplateView):

    template_name = "sport_events/sport_events_home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


# Odd even change remaining in scheduling
@login_required
@user_passes_test(lambda u:u.is_staff)
@transaction.atomic
def schedule(request,pk):
    event = get_object_or_404(Event, pk=pk)

    participants = []

    if event.curr_round==0:
        participants = [p for p in event.participants.all()]
    else:
        participants = [p.winner for p in event.matches.filter(round_no=event.curr_round)]
        
        for p in participants:
            if p is None:
                # set some message
                return redirect(reverse('sport_events:event_detail', kwargs={'pk':pk}))

    l = len(participants)
    
    if l==1:
        event.complete()
        event.save()
        return EventDetailView.as_view()(request, pk=pk)
        # return redirect(reverse('sport_events:event_detail', kwargs={'pk':pk}))

    event.curr_round = event.curr_round + 1
    event.save()

    i=0
    while i+1 < l:
        Match(event=event,participant_1=participants[i],participant_2=participants[i+1],
                round_no=event.curr_round).save()
        i=i+2

    if i<l:
        Match(event=event,participant_1=participants[i],
                round_no=event.curr_round).save()
    
    return redirect(reverse('sport_events:event_detail', kwargs={'pk':pk}))



@method_decorator([login_required, user_passes_test(lambda u:u.is_staff)], name='dispatch')
class MatchUpdateView(UpdateView):
    model = Match
    # fields="__all__"
    form_class = MatchForm
    template_name = "sport_events/match_update.html"

sport_events/templates/sport_events/active_events_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for event in event_list %}
        <a href="{% url 'sport_events:event_detail' event.pk %}">{{event.name}}</a>
    {% endfor %}
</body>
</html>

sport_events/templates/sport_events/closed_events_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for event in event_list %}
        <a href="{% url 'sport_events:event_detail' event.pk %}">{{event.name}}</a>
    {% endfor %}
</body>
</html>

sport_events/templates/sport_events/completed_events_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for event in event_list %}
        <a href="{% url 'sport_events:event_detail' event.pk %}">{{event.name}}</a>
    {% endfor %}
</body>
</html>

sport_events/templates/sport_events/event_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        {{object.name}}<br> 
        {{object.sport}}<br> 
        {{object.fee}}<br> 
        {{object.eligible_user_type}}<br> 
        {{object.status}}<br>
        <br><br>


        {% if object.status|stringformat:"s" == 'ACTIVE' %}

            {% if is_registered %}
                <p>Registered</p>
            {% elif not user.is_staff%}
                <a href="{% url 'sport_events:register' object.pk %}">Register</a>
            {% endif %}

        {% elif object.status|stringformat:"s" == 'CLOSED' %}

            Round {{ object.curr_round }}
            <table width="100%">
                <tr>
                    <th>Participant 1</th>
                    <th>Participant 2</th>
                    <th>Winner</th>
                    <th></th>
                </tr>
                
                {% for match in matches %}
                <tr>
                    <td>{{ match.participant_1.username }}</td>
                    <td>{{ match.participant_2.username }}</td>
                    <td>{{ match.winner.username }}</td>
                    {% if user.is_staff %}
                        <td><a href="{% url 'sport_events:match_update' match.pk %}">Update</a></td>                    
                    {% endif %}
                </tr>
                {% endfor %}
            </table> 

            {% if user.is_staff %}
                <a href="{% url 'sport_events:schedule' object.pk %}">Schedule Round</a>            
            {% endif %}

        {% elif object.status|stringformat:"s" == 'COMPLETED' %}

            Winner : {{ winner.username }}

        {% endif %}



</body>
</html>

sport_events/templates/sport_events/match_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</body>
</html>

sport_events/templates/sport_events/my_events_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for event in event_list %}
        <a href="{% url 'sport_events:event_detail' event.pk %}">{{event.name}}</a>
    {% endfor %}
</body>
</html>

sport_events/templates/sport_events/sport_events_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sport Events Home</title>
</head>
<body>
    
    {% if user.is_authenticated %}
        <p>
            <a href="{% url 'sport_events:my_events' %}">My Events</a>
        </p>    
    {% endif %}

    <p>
        <a href="{% url 'sport_events:active_events' %}">Active Events</a>
    </p>
    <p>
        <a href="{% url 'sport_events:closed_events' %}">Closed Events</a>
    </p>
    <p>
        <a href="{% url 'sport_events:completed_events' %}">Completed Events</a>
    </p>

</body>
</html>