EventReg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('users/', include('users.urls')), 
    path('users/', include('django.contrib.auth.urls')),
    
    # we want to have our home.html template appear as the homepage. But we don’t want to build a
    # dedicated pages app just yet, so we can use the shortcut of importing TemplateView
    # and setting the template_name right in our url pattern
    path('', TemplateView.as_view(template_name='home.html'),name='home'), 

    path('sport_events/',include(('sport_events.urls','sport_events'),namespace='sport_events'), name='sport_events'),
]

sport_events/urls.py
from django.urls import path
from sport_events import views

app_name = 'sport_events'

urlpatterns = [
    path('', views.SportEventsHomeView.as_view(), name='sport_events_home'),
    
    path('active_events/', views.ActiveEventListView.as_view(), name='active_events'),
    path('closed_events/', views.ClosedEventListView.as_view(), name='closed_events'),
    path('completed_events/', views.CompletedEventListView.as_view(), name='completed_events'),
    path('my_events/', views.MyEventListView.as_view() , name='my_events'),
    
    path('event/<int:pk>/', views.EventDetailView.as_view() , name='event_detail'),
    path('event/<int:pk>/register/', views.register , name='register'),
    path('event/<int:pk>/schedule/', views.schedule , name='schedule'),

    path('match/<int:pk>/update/', views.MatchUpdateView.as_view() , name='match_update'),
]

users/urls.py
from django.urls import path
from users.views import SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{% block title %}Sport Events Management System{% endblock title %}</title>
</head>
<body>
<main>
{% block content %}
{% endblock content %}
</main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
    <h2>Profile</h2>
    Hi {{ user.username }}!
    <p><a href="{% url 'password_change' %}">Change Password</a></p>
    <p><a href="{% url 'logout' %}">Log Out</a></p>
    <a href="{% url 'sport_events:sport_events_home' %}">Go to Sport Events</a>
{% else %}
    <p>Log in / Sign Up to get started</p>
    <a href="{% url 'login' %}">Log In</a><br>
    <a href="{% url 'users:signup' %}">Sign Up</a> <br>
{% endif %}
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
</form>

{% endblock content %}